### ISSUE TITLE
Help understanding error message in permuspliner

### ISSUE THREAD

**Issue by ctSkennerton** [RRShieldsCutler/splinectomeR#1]
Hi,

I'm trying to follow the protocol presented in [your vignette](https://rrshieldscutler.github.io/splinectomeR/yassour_antibiotics_web.html) with some of my own data and I get the following error:
```
permuspliner(data = sphingobium, xvar = 'Date', yvar = 'Abundance', category = 'Category', cases = 'Identifier', groups=c('SS-25_well', 'Bkg_surr'), cut_low = 4, perms = 99)

Groups detected: SS-25_well and Bkg_surr .

Now testing between variables SS-25_well and Bkg_surr for a difference in the response labeled Abundance 

Scalpel please: performing permusplinectomy with 99 permutations...

Area between groups successfully calculated, now spinning up permutations...
Error in smooth.spline(x = randy_v1[, xvar], y = randy_v1[, yvar], spar = set_spar,  : 
  need at least four unique 'x' values
```

I'm not sure here what the "x values" are. In my original data I believe I have more than 4 dates, which is what I'm passing in as the `xvar` to `permuspliner `

For reference, I'm attaching my data: 
[sphingobium.rds.gz](https://github.com/RRShieldsCutler/splinectomeR/files/2074358/sphingobium.rds.gz)

I'm sure it's something simple I've misunderstood.

Best,
Connor

**Comment by ctSkennerton** [comment]
My apologies, I found that it was an issue with my data.

**Comment by RRShieldsCutler** [comment]
No problem, glad it was resolved!
