### ISSUE TITLE
How does splinectomeR handle missing values for a subject?

### ISSUE THREAD

**Issue by reaset41** [RRShieldsCutler/splinectomeR#12]
I am working with a dataset with 4 timepoints. Not every subject has a sample for each timepoint. How does splinectomeR handle missing values for a subject?

**Comment by RRShieldsCutler** [comment]
Hello! The spline connects existing points by fitting those to the curve. Any 'intermediate' points are essentially points along that spline. What was a series of 4 (or 3) data points becomes an interpolated, smoothed curve. Consider when evaluating what/how much to conclude/interpret (as with any analysis), that four timepoints is kind of on the low end, particularly if there are many missing values, and depending on number of subjects etc. Cheers!
