### ISSUE TITLE
trendyspliner returns pvalues either 0.001 or 0.002

### ISSUE THREAD

**Issue by rjg2186** [RRShieldsCutler/splinectomeR#3]
@RRShieldsCutler 
I am using trendyspliner to test a response in one group (here, feeding_in_hospital == "OnlyFormula") over time for each of the bacterium family. When i run through the method using the commands as shown below, i get pvalue either 0.001 or 0.002 only. When i change the feeding_in_hospital == "mixed", i do get pvalues either 0.001 or 0.002. I am little confused on how to interpret the results. Not sure if the input or parameters are correct. Can you please help to understand the output.
Thanks

```
top20_family_meta <- top20_family_meta[which(top20_family_meta$feeding_in_hospital == "OnlyFormula"),]


f_top20_abx_pvals <- list()
for (f in unique(top20_family_meta$family)) {
  f__df <- top20_family_meta %>% filter(family == f)
  
  set.seed(123456)
  f.result <- trendyspliner(data = f__df,
                               xvar = 'timepoint', quiet = T, cases = 'baby_id',
                               mean_center = T, yvar = 'relative_abundance', perms = 999)
  message(f, " : ",f.result$pval)
  f_top20_abx_pvals <- append(f_top20_abx_pvals, f.result$pval)
}
```

**Output**

```
k__Archaea.p__Euryarchaeota.c__Methanobacteria.o__Methanobacteriales.f__Methanobacteriaceae : 0.002
k__Bacteria.p__Actinobacteria.c__Actinobacteria.o__Actinomycetales.f__Actinomycetaceae : 0.002
k__Bacteria.p__Actinobacteria.c__Actinobacteria.o__Actinomycetales.f__Corynebacteriaceae : 0.001
k__Bacteria.p__Actinobacteria.c__Actinobacteria.o__Actinomycetales.f__Microbacteriaceae : 0.002
k__Bacteria.p__Actinobacteria.c__Actinobacteria.o__Actinomycetales.f__Micrococcaceae : 0.002
k__Bacteria.p__Actinobacteria.c__Actinobacteria.o__Bifidobacteriales.f__Bifidobacteriaceae : 0.001
k__Bacteria.p__Actinobacteria.c__Coriobacteriia.o__Coriobacteriales.f__Coriobacteriaceae : 0.001
k__Bacteria.p__Bacteroidetes.c__Bacteroidia.o__Bacteroidales.f__Bacteroidaceae : 0.001
k__Bacteria.p__Bacteroidetes.c__Bacteroidia.o__Bacteroidales.f__Porphyromonadaceae : 0.001
k__Bacteria.p__Bacteroidetes.c__Bacteroidia.o__Bacteroidales.f__Prevotellaceae : 0.002



```

**Comment by RRShieldsCutler** [comment]
Sure, a couple of things here. First, given the biology of this particular study, it's not surprising that the taxa are changing non-linearly. That's what this test is looking at -- whether the trend in the feature is changing from it's baseline significantly over time. Here, you have infants who are going through the most dramatic changes in gut composition that many people will ever experience; so, you would probably expect most bugs to be either going up or down over that period. We've used this test to look at some measures (e.g. alpha diversity level) over time in an adult cohort, where we often see non-significant results.

Second, I'd recommend adjusting for multiple comparisons after doing a looped test like this. If you store all the pvalues into a numeric vector, you can use `p.adjust(x, method='fdr'), where `x` is your pvalue vector, to get the FDR-corrected p-values.

Hope that helps!

**Comment by rjg2186** [comment]
@RRShieldsCutler 
Thanks for the clarification. 
I will check with FDR
