### ISSUE TITLE
Using more than one category

### ISSUE THREAD

**Issue by rjg2186** [RRShieldsCutler/splinectomeR#4]
@RRShieldsCutler 
Can you please let me know if it is possible to test simultaneously for more than one category across the time points ?
Example, for the following metadata from tutorial, is it possible to use both categories "birth_mode" and "feeding_in_hospital" simultaneously across all the time points.

```
> head(general_metadata)
  #Sample_ID birth_year    sex        birth_mode gestational_age
1    E000823       2008   Male  Vaginal delivery            39+4
2    E001958       2008 Female  Vaginal delivery            40+1
3    E003188       2008 Female  Vaginal delivery            38+6
4    E003953       2008 Female  Vaginal delivery            39+5
5    E004628       2008   Male Ceasarean section            40+3
6    E004709       2008   Male  Vaginal delivery            40+2
  months_final_exclusive_breastfeeding months_end_breastfeeding
1                                  5.0                    13.02
2                                  0.0                    12.66
3                                  5.0                    13.28
4                                  3.0                     6.98
5                                  0.5                     4.46
6                                  0.0                     7.97
  months_started_formula_feeding feeding_in_hospital
1                             NA      OnlyBreastmilk
2                             NA               mixed
3                           10.0      OnlyBreastmilk
4                            3.0      OnlyBreastmilk
5                            0.5      OnlyBreastmilk
6                            0.0               mixed
```
Thanks

**Comment by RRShieldsCutler** [comment]
Not at this time, at least not directly. The way that the difference between groups is evaluated makes that challenging, as well as interpretation. You could create combined groups by pasting the two categories' values together into a new column, e.g. "birth_mode = Vaginal delivery" and "feeding_in_hospital = mixed" would be "birth_mode_and_feeding = Vaginal delivery_mixed". Then, you could run the tests between the pairs of groups (and adjust for multiple comparisons). I would recommend plotting those groups first to see if it looks like it's worth trying the test (do they look different?). Also, the further you subset some of these groups, the smaller and less robust the tests will be.
