### ISSUE TITLE
x-axis ticks in trendyspliner

### ISSUE THREAD

**Issue by acmasche** [RRShieldsCutler/splinectomeR#6]
Hi @RRShieldsCutler 
Thank you for this very useful package. 

I am wondering if there is a reason for the limits of the x-axis ticks in trendyspliner. 

I ran trendyspliner with the ChickWeight example data like this: 
```{r}
data("ChickWeight")
set.seed(100)
result <- trendyspliner(data = ChickWeight, x = 'Time', y = 'weight', cases = 'Chick', category = 'Diet', group = '1', perms = 999)
```
and then made a plot like this: 
```{r}
result_plot <- trendyspliner.plot.perms(result)
result_plot
```
Then I looked for the x-axis limits of the plot:
```{r}
layer_scales(result_plot)$x$range$range
```

This yields a min of 1.0500 and a max of 20.0025

However, ```range(ChickWeight$Time)``` is from 0 to 21. 

Is there a reason that this does not match? 

I had the same issue with my own data, and when I replace the default x-axis ticks, the first and last label are not covered by the plot. 

Thanks in advance for your help.

**Comment by RRShieldsCutler** [comment]
Hello! Thanks for the question. Yes, you are not imagining things... essentially, this was implemented to help minimize the effect of 'flying tails' that spline fits often end up with at the beginning and ending of the data (if you have plotted splines on a noisy dataset, you may be familiar with the exponentially expanding CI interval as the line becomes fit to fewer points). Worry not, the spline is initially fit to your entire dataset, but the first and last 5% of the imputed traces (not the raw data) are trimmed for cleaner comparison and visualization. Possible this could be made an optional behavior in the future.. Thanks again!

**Comment by acmasche** [comment]
Thank you for the quick reply. That makes sense, indeed.
