### ISSUE TITLE
Error with sliding_spliner()

### ISSUE THREAD

**Issue by shathab** [RRShieldsCutler/splinectomeR#7]
When I use sliding_spliner(), I get the following error:

Warning in min(as.numeric(df[, xvar])) :
  no non-missing arguments to min; returning Inf
Warning in max(as.numeric(df[, xvar])) :
  no non-missing arguments to max; returning -Inf
Error in seq.default(from = x.min, to = x.max, by = ((x.max - x.min)/(ints -  : 
  'from' must be a finite number

Thank you in advance for your help!

**Comment by RRShieldsCutler** [comment]
Hello! Been swamped with covid-related changes, apologies. Hard to say too precisely on the error without more information about the dataset, but I believe I've seen this crop up when some of the data doesn't have enough points - to make the comparison between groups, for example. You could try to reduce the test_density parameter (though anything less than 3 isn't a great comparison statistically) and/or check that the groups have enough samples represented throughout the time series to make those comparisons. This one can be admittedly finicky with more sparse datasets or low _n_...
