### ISSUE TITLE
issue with p values from trendyspliner

### ISSUE THREAD

**Issue by ghost** [RRShieldsCutler/splinectomeR#8]
Hello, 

When I feed trendyspliner a vector of 0's it gives me a significant p value; in fact, it gives me a significant p value in all cases I have tried. I am using the latest version installed from github. Permuspliner will give a non significant value if fed a vector of 0's (no variation between two groups).

**Comment by RRShieldsCutler** [comment]
Apologies this took so long! Thanks for the catch and working with me on this! Latest release is updated with the patch.
